service:
  port: 8080
spring:
  spring:
    jackson:
      serialization:
        FAIL_ON_EMPTY_BEANS: false
  datasource:
    url: jdbc:mysql://localhost:13306/taskdb
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
    show-sql: true

